"""Infrastructure layer - concrete repository implementations.

Available repositories:
- InMemoryWorldRepository, InMemoryCharacterRepository, etc. (in_memory_repositories.py)
- SQLiteWorldRepository, SQLiteCharacterRepository, etc. (sqlite_repositories.py)
"""

from .in_memory_repositories import (
    InMemoryWorldRepository,
    InMemoryCharacterRepository,
    InMemoryStoryRepository,
    InMemoryEventRepository,
    InMemoryPageRepository,
    InMemoryItemRepository,
    InMemoryLocationRepository,
    InMemoryEnvironmentRepository,
    InMemoryTextureRepository,
    InMemoryModel3DRepository,
)

from .sqlite_repositories import (
    SQLiteDatabase,
    SQLiteWorldRepository,
    SQLiteCharacterRepository,
    SQLiteStoryRepository,
    SQLiteEventRepository,
    SQLitePageRepository,
    SQLiteItemRepository,
    SQLiteLocationRepository,
    SQLiteEnvironmentRepository,
    SQLiteTextureRepository,
    SQLiteModel3DRepository,
    SQLiteSessionRepository,
    SQLiteTagRepository,
    SQLiteNoteRepository,
    SQLiteTemplateRepository,
    SQLiteChoiceRepository,
    SQLiteFlowchartRepository,
    SQLiteHandoutRepository,
    SQLiteImageRepository,
    SQLiteInspirationRepository,
    SQLiteMapRepository,
    SQLiteTokenboardRepository,
)

__all__ = [
    # In-memory repositories (for testing)
    'InMemoryWorldRepository',
    'InMemoryCharacterRepository',
    'InMemoryStoryRepository',
    'InMemoryEventRepository',
    'InMemoryPageRepository',
    'InMemoryItemRepository',
    'InMemoryLocationRepository',
    'InMemoryEnvironmentRepository',
    'InMemoryTextureRepository',
    'InMemoryModel3DRepository',
    'InMemorySessionRepository',
    'InMemoryTagRepository',
    'InMemoryNoteRepository',
    'InMemoryTemplateRepository',
    'InMemoryChoiceRepository',
    'InMemoryFlowchartRepository',
    'InMemoryHandoutRepository',
    'InMemoryImageRepository',
    'InMemoryInspirationRepository',
    'InMemoryMapRepository',
    'InMemoryTokenboardRepository',

    # SQLite repositoriesfrom src.infrastructure.in_memory_repositories import QuestChain
from src.infrastructure.in_memory_repositories import QuestNode
from src.infrastructure.in_memory_repositories import QuestPrerequisite
from src.infrastructure.in_memory_repositories import QuestObjective
from src.infrastructure.in_memory_repositories import QuestTracker
from src.infrastructure.in_memory_repositories import QuestGiver
from src.infrastructure.in_memory_repositories import QuestReward
from src.infrastructure.in_memory_repositories import QuestRewardTier
from src.infrastructure.sqlite_repositories import SQLiteQuestChain
from src.infrastructure.sqlite_repositories import SQLiteQuestNode
from src.infrastructure.sqlite_repositories import SQLiteQuestPrerequisite
from src.infrastructure.sqlite_repositories import SQLiteQuestObjective
from src.infrastructure.sqlite_repositories import SQLiteQuestTracker
from src.infrastructure.sqlite_repositories import SQLiteQuestGiver
from src.infrastructure.sqlite_repositories import SQLiteQuestReward
from src.infrastructure.sqlite_repositories import SQLiteQuestRewardTier (for production)
    'SQLiteDatabase',
    'SQLiteWorldRepository',
    'SQLiteCharacterRepository',
    'SQLiteStoryRepository',
    'SQLiteEventRepository',
    'SQLitePageRepository',
    'SQLiteItemRepository',
    'SQLiteLocationRepository',
    'SQLiteEnvironmentRepository',
    'SQLiteTextureRepository',
    'SQLiteModel3DRepository',
    'SQLiteSessionRepository',
    'SQLiteTagRepository',
    'SQLiteNoteRepository',
    'SQLiteTemplateRepository',
    'SQLiteChoiceRepository',
    'SQLiteFlowchartRepository',
    'SQLiteHandoutRepository',
    'SQLiteImageRepository',
    'SQLiteInspirationRepository',
    'SQLiteMapRepository',
    'SQLiteTokenboardRepository',
]


# Quest repositories
    'SQLiteQuestChain',
    'SQLiteQuestNode',
    'SQLiteQuestPrerequisite',
    'SQLiteQuestObjective',
    'SQLiteQuestTracker',
    'SQLiteQuestGiver',
    'SQLiteQuestReward',
    'SQLiteQuestRewardTier',


# Quest repositories
    InMemoryQuestChain,
    InMemoryQuestNode,
    InMemoryQuestPrerequisite,
    InMemoryQuestObjective,
    InMemoryQuestTracker,
    InMemoryQuestGiver,
    InMemoryQuestReward,
    InMemoryQuestRewardTier,

    SQLiteQuestChain,
    SQLiteQuestNode,
    SQLiteQuestPrerequisite,
    SQLiteQuestObjective,
    SQLiteQuestTracker,
    SQLiteQuestGiver,
    SQLiteQuestReward,
    SQLiteQuestRewardTier,

from src.infrastructure.in_memory_repositories import Skill
from src.infrastructure.in_memory_repositories import Perk
from src.infrastructure.in_memory_repositories import Trait
from src.infrastructure.in_memory_repositories import Attribute
from src.infrastructure.in_memory_repositories import Experience
from src.infrastructure.in_memory_repositories import LevelUp
from src.infrastructure.in_memory_repositories import TalentTree
from src.infrastructure.in_memory_repositories import Mastery
from src.infrastructure.in_memory_repositories import FactionHierarchy
from src.infrastructure.in_memory_repositories import FactionIdeology
from src.infrastructure.in_memory_repositories import FactionLeader
from src.infrastructure.in_memory_repositories import FactionMembership
from src.infrastructure.in_memory_repositories import FactionResource
from src.infrastructure.in_memory_repositories import FactionTerritory
from src.infrastructure.sqlite_repositories import SQLiteSkill
from src.infrastructure.sqlite_repositories import SQLitePerk
from src.infrastructure.sqlite_repositories import SQLiteTrait
from src.infrastructure.sqlite_repositories import SQLiteAttribute
from src.infrastructure.sqlite_repositories import SQLiteExperience
from src.infrastructure.sqlite_repositories import SQLiteLevelUp
from src.infrastructure.sqlite_repositories import SQLiteTalentTree
from src.infrastructure.sqlite_repositories import SQLiteMastery
from src.infrastructure.sqlite_repositories import SQLiteFactionHierarchy
from src.infrastructure.sqlite_repositories import SQLiteFactionIdeology
from src.infrastructure.sqlite_repositories import SQLiteFactionLeader
from src.infrastructure.sqlite_repositories import SQLiteFactionMembership
from src.infrastructure.sqlite_repositories import SQLiteFactionResource
from src.infrastructure.sqlite_repositories import SQLiteFactionTerritory
# Progression repositories
    Skill,
    Perk,
    Trait,
    Attribute,
    Experience,
    LevelUp,
    TalentTree,
    Mastery,

# Faction repositories
    FactionHierarchy,
    FactionIdeology,
    FactionLeader,
    FactionMembership,
    FactionResource,
    FactionTerritory,
# Progression repositories
    SQLiteSkill,
    SQLitePerk,
    SQLiteTrait,
    SQLiteAttribute,
    SQLiteExperience,
    SQLiteLevelUp,
    SQLiteTalentTree,
    SQLiteMastery,

# Faction repositories
    SQLiteFactionHierarchy,
    SQLiteFactionIdeology,
    SQLiteFactionLeader,
    SQLiteFactionMembership,
    SQLiteFactionResource,
    SQLiteFactionTerritory,

from src.infrastructure.in_memory_repositories import InMemoryMiracleRepository
from src.infrastructure.in_memory_repositories import InMemoryCourtRepository
from src.infrastructure.in_memory_repositories import InMemoryVoice_overRepository
from src.infrastructure.in_memory_repositories import InMemoryFestivalRepository
from src.infrastructure.in_memory_repositories import InMemoryCataclysmRepository
from src.infrastructure.in_memory_repositories import InMemoryProgression_stateRepository
from src.infrastructure.in_memory_repositories import InMemoryChapterRepository
from src.infrastructure.in_memory_repositories import InMemoryAttributeRepository
from src.infrastructure.in_memory_repositories import InMemoryNationRepository
from src.infrastructure.in_memory_repositories import InMemoryStoryRepository
from src.infrastructure.in_memory_repositories import InMemoryEvidenceRepository
from src.infrastructure.in_memory_repositories import InMemoryImprovementRepository
from src.infrastructure.in_memory_repositories import InMemoryLore_fragmentRepository
from src.infrastructure.in_memory_repositories import InMemoryFactionRepository
from src.infrastructure.in_memory_repositories import InMemoryConcertRepository
from src.infrastructure.in_memory_repositories import InMemoryAllianceRepository
from src.infrastructure.in_memory_repositories import InMemorySkillRepository
from src.infrastructure.in_memory_repositories import InMemoryCinematicRepository
from src.infrastructure.in_memory_repositories import InMemoryDemandRepository
from src.infrastructure.in_memory_repositories import InMemoryNoteRepository
from src.infrastructure.in_memory_repositories import InMemoryDeus_ex_machinaRepository
from src.infrastructure.in_memory_repositories import InMemorySeasonRepository
from src.infrastructure.in_memory_repositories import InMemoryFlash_forwardRepository
from src.infrastructure.in_memory_repositories import InMemoryWorldRepository
from src.infrastructure.in_memory_repositories import InMemoryTalent_treeRepository
from src.infrastructure.in_memory_repositories import InMemoryQuestRepository
from src.infrastructure.in_memory_repositories import InMemoryLegendary_weaponRepository
from src.infrastructure.in_memory_repositories import InMemoryGlyphRepository
from src.infrastructure.in_memory_repositories import InMemoryRelic_collectionRepository
from src.infrastructure.in_memory_repositories import InMemoryArtifact_setRepository
from src.infrastructure.in_memory_repositories import InMemoryDifficulty_curveRepository
from src.infrastructure.in_memory_repositories import InMemoryRequirementRepository
from src.infrastructure.in_memory_repositories import InMemoryPlot_deviceRepository
from src.infrastructure.in_memory_repositories import InMemoryBannerRepository
from src.infrastructure.in_memory_repositories import InMemoryQuest_rewardRepository
from src.infrastructure.in_memory_repositories import InMemoryJudgeRepository
from src.infrastructure.in_memory_repositories import InMemoryNightmareRepository
from src.infrastructure.in_memory_repositories import InMemorySecret_areaRepository
from src.infrastructure.in_memory_repositories import InMemoryPactRepository
from src.infrastructure.in_memory_repositories import InMemoryWarRepository
from src.infrastructure.in_memory_repositories import InMemoryUser_scenarioRepository
from src.infrastructure.in_memory_repositories import InMemoryVisual_effectRepository
from src.infrastructure.in_memory_repositories import InMemoryMaterialRepository
from src.infrastructure.in_memory_repositories import InMemorySave_pointRepository
from src.infrastructure.in_memory_repositories import InMemoryPropagandaRepository
from src.infrastructure.in_memory_repositories import InMemoryLeaderboardRepository
from src.infrastructure.in_memory_repositories import InMemoryEclipseRepository
from src.infrastructure.in_memory_repositories import InMemoryBalance_entitiesRepository
from src.infrastructure.in_memory_repositories import InMemoryPunishmentRepository
from src.infrastructure.in_memory_repositories import InMemoryUndergroundRepository
from src.infrastructure.in_memory_repositories import InMemoryRadioRepository
from src.infrastructure.in_memory_repositories import InMemoryBestiary_entryRepository
from src.infrastructure.in_memory_repositories import InMemoryOpen_world_zoneRepository
from src.infrastructure.in_memory_repositories import InMemoryRewardRepository
from src.infrastructure.in_memory_repositories import InMemoryDrop_rateRepository
from src.infrastructure.in_memory_repositories import InMemoryMusic_themeRepository
from src.infrastructure.in_memory_repositories import InMemoryConstitutionRepository
from src.infrastructure.in_memory_repositories import InMemoryDefenseRepository
from src.infrastructure.in_memory_repositories import InMemoryInvasionRepository
from src.infrastructure.in_memory_repositories import InMemoryInspirationRepository
from src.infrastructure.in_memory_repositories import InMemoryLoot_table_weightRepository
from src.infrastructure.in_memory_repositories import InMemoryDiscoveryRepository
from src.infrastructure.in_memory_repositories import InMemoryMountRepository
from src.infrastructure.in_memory_repositories import InMemoryWormholeRepository
from src.infrastructure.in_memory_repositories import InMemoryPocket_dimensionRepository
from src.infrastructure.in_memory_repositories import InMemoryEvent_chainRepository
from src.infrastructure.in_memory_repositories import InMemoryPrologueRepository
from src.infrastructure.in_memory_repositories import InMemoryFadeRepository
from src.infrastructure.in_memory_repositories import InMemoryAutosaveRepository
from src.infrastructure.in_memory_repositories import InMemoryPerkRepository
from src.infrastructure.in_memory_repositories import InMemorySocial_mobilityRepository
from src.infrastructure.in_memory_repositories import InMemoryCharacter_profile_entryRepository
from src.infrastructure.in_memory_repositories import InMemoryModel3dRepository
from src.infrastructure.in_memory_repositories import InMemorySoundtrackRepository
from src.infrastructure.in_memory_repositories import InMemoryTagRepository
from src.infrastructure.in_memory_repositories import InMemoryInflationRepository
from src.infrastructure.in_memory_repositories import InMemoryStar_systemRepository
from src.infrastructure.in_memory_repositories import InMemoryQuarterRepository
from src.infrastructure.in_memory_repositories import InMemoryPurchaseRepository
from src.infrastructure.in_memory_repositories import InMemoryCharacter_relationshipRepository
from src.infrastructure.in_memory_repositories import InMemoryGovernmentRepository
from src.infrastructure.in_memory_repositories import InMemoryCampaignRepository
from src.infrastructure.in_memory_repositories import InMemoryEventRepository
from src.infrastructure.in_memory_repositories import InMemoryPityRepository
from src.infrastructure.in_memory_repositories import InMemoryImageRepository
from src.infrastructure.in_memory_repositories import InMemoryTranslationRepository
from src.infrastructure.in_memory_repositories import InMemoryColor_paletteRepository
from src.infrastructure.in_memory_repositories import InMemorySeasonal_eventRepository
from src.infrastructure.in_memory_repositories import InMemoryArmyRepository
from src.infrastructure.in_memory_repositories import InMemoryModRepository
from src.infrastructure.in_memory_repositories import InMemoryBlueprintRepository
from src.infrastructure.in_memory_repositories import InMemoryQuest_trackerRepository
from src.infrastructure.in_memory_repositories import InMemoryRankRepository
from src.infrastructure.in_memory_repositories import InMemoryCelebrationRepository
from src.infrastructure.in_memory_repositories import InMemoryItemRepository
from src.infrastructure.in_memory_repositories import InMemoryCurseRepository
from src.infrastructure.in_memory_repositories import InMemoryHub_areaRepository
from src.infrastructure.in_memory_repositories import InMemoryLocationRepository
from src.infrastructure.in_memory_repositories import InMemoryRevolutionRepository
from src.infrastructure.in_memory_repositories import InMemoryFaction_resourceRepository
from src.infrastructure.in_memory_repositories import InMemoryTreatyRepository
from src.infrastructure.in_memory_repositories import InMemoryAirshipRepository
from src.infrastructure.in_memory_repositories import InMemoryCultRepository
from src.infrastructure.in_memory_repositories import InMemoryEnchantmentRepository
from src.infrastructure.in_memory_repositories import InMemoryInstanceRepository
from src.infrastructure.in_memory_repositories import InMemoryAcademyRepository
from src.infrastructure.in_memory_repositories import InMemorySilenceRepository
from src.infrastructure.in_memory_repositories import InMemoryLore_axiomsRepository
from src.infrastructure.in_memory_repositories import InMemorySupplyRepository
from src.infrastructure.in_memory_repositories import InMemoryFaction_membershipRepository
from src.infrastructure.in_memory_repositories import InMemoryMusic_stateRepository
from src.infrastructure.in_memory_repositories import InMemoryBlessingRepository
from src.infrastructure.in_memory_repositories import InMemoryPrototypeRepository
from src.infrastructure.in_memory_repositories import InMemoryFaction_ideologyRepository
from src.infrastructure.in_memory_repositories import InMemoryKarmaRepository
from src.infrastructure.in_memory_repositories import InMemoryCharacter_variantRepository
from src.infrastructure.in_memory_repositories import InMemoryLegal_systemRepository
from src.infrastructure.in_memory_repositories import InMemoryQuest_objectiveRepository
from src.infrastructure.in_memory_repositories import InMemoryPlot_branchRepository
from src.infrastructure.in_memory_repositories import InMemoryWaypointRepository
from src.infrastructure.in_memory_repositories import InMemoryProgression_eventRepository
from src.infrastructure.in_memory_repositories import InMemoryNewspaperRepository
from src.infrastructure.in_memory_repositories import InMemoryWardRepository
from src.infrastructure.in_memory_repositories import InMemoryMemoryRepository
from src.infrastructure.in_memory_repositories import InMemoryPullRepository
from src.infrastructure.in_memory_repositories import InMemoryHandoutRepository
from src.infrastructure.in_memory_repositories import InMemoryBranch_pointRepository
from src.infrastructure.in_memory_repositories import InMemoryWorld_eventRepository
from src.infrastructure.in_memory_repositories import InMemorySectRepository
from src.infrastructure.in_memory_repositories import InMemoryEmpireRepository
from src.infrastructure.in_memory_repositories import InMemoryQuest_chainRepository
from src.infrastructure.in_memory_repositories import InMemoryChoiceRepository
from src.infrastructure.in_memory_repositories import InMemoryRuneRepository
from src.infrastructure.in_memory_repositories import InMemoryHolidayRepository
from src.infrastructure.in_memory_repositories import InMemoryShaderRepository
from src.infrastructure.in_memory_repositories import InMemoryTitleRepository
from src.infrastructure.in_memory_repositories import InMemoryPlayer_metricRepository
from src.infrastructure.in_memory_repositories import InMemoryEpilogueRepository
from src.infrastructure.in_memory_repositories import InMemoryMysteryRepository
from src.infrastructure.in_memory_repositories import InMemoryWeather_patternRepository
from src.infrastructure.in_memory_repositories import InMemoryActRepository
from src.infrastructure.in_memory_repositories import InMemoryEpisodeRepository
from src.infrastructure.in_memory_repositories import InMemoryTelevisionRepository
from src.infrastructure.in_memory_repositories import InMemorySiege_engineRepository
from src.infrastructure.in_memory_repositories import InMemoryCustom_mapRepository
from src.infrastructure.in_memory_repositories import InMemoryThemeRepository
from src.infrastructure.in_memory_repositories import InMemoryCrafting_recipeRepository
from src.infrastructure.in_memory_repositories import InMemorySocial_classRepository
from src.infrastructure.in_memory_repositories import InMemoryFaction_leaderRepository
from src.infrastructure.in_memory_repositories import InMemoryRiddleRepository
from src.infrastructure.in_memory_repositories import InMemoryFast_travel_pointRepository
from src.infrastructure.in_memory_repositories import InMemoryMuseumRepository
from src.infrastructure.in_memory_repositories import InMemoryTraitRepository
from src.infrastructure.in_memory_repositories import InMemoryFamiliarRepository
from src.infrastructure.in_memory_repositories import InMemoryEra_transitionRepository
from src.infrastructure.in_memory_repositories import InMemoryTariffRepository
from src.infrastructure.in_memory_repositories import InMemoryQuest_nodeRepository
from src.infrastructure.in_memory_repositories import InMemoryDreamRepository
from src.infrastructure.in_memory_repositories import InMemoryHoly_siteRepository
from src.infrastructure.in_memory_repositories import InMemoryInventoryRepository
from src.infrastructure.in_memory_repositories import InMemoryAffinityRepository
from src.infrastructure.in_memory_repositories import InMemoryAlternate_realityRepository
from src.infrastructure.in_memory_repositories import InMemoryMount_equipmentRepository
from src.infrastructure.in_memory_repositories import InMemorySound_effectRepository
from src.infrastructure.in_memory_repositories import InMemoryInternetRepository
from src.infrastructure.in_memory_repositories import InMemoryTime_periodRepository
from src.infrastructure.in_memory_repositories import InMemorySessionRepository
from src.infrastructure.in_memory_repositories import InMemoryExperienceRepository
from src.infrastructure.in_memory_repositories import InMemoryPuzzleRepository
from src.infrastructure.in_memory_repositories import InMemoryMotion_captureRepository
from src.infrastructure.in_memory_repositories import InMemoryFortificationRepository
from src.infrastructure.in_memory_repositories import InMemoryVoice_actorRepository
from src.infrastructure.in_memory_repositories import InMemoryDimensionRepository
from src.infrastructure.in_memory_repositories import InMemoryMusic_controlRepository
from src.infrastructure.in_memory_repositories import InMemoryDubbingRepository
from src.infrastructure.in_memory_repositories import InMemoryHidden_pathRepository
from src.infrastructure.in_memory_repositories import InMemoryFleetRepository
from src.infrastructure.in_memory_repositories import InMemorySocial_mediaRepository
from src.infrastructure.in_memory_repositories import InMemoryBarterRepository
from src.infrastructure.in_memory_repositories import InMemoryCalendarRepository
from src.infrastructure.in_memory_repositories import InMemorySolsticeRepository
from src.infrastructure.in_memory_repositories import InMemorySchoolRepository
from src.infrastructure.in_memory_repositories import InMemorySlumsRepository
from src.infrastructure.in_memory_repositories import InMemoryDisasterRepository
from src.infrastructure.in_memory_repositories import InMemoryMasteryRepository
from src.infrastructure.in_memory_repositories import InMemoryPageRepository
from src.infrastructure.in_memory_repositories import InMemoryMotifRepository
from src.infrastructure.in_memory_repositories import InMemorySpawn_pointRepository
from src.infrastructure.in_memory_repositories import InMemoryWorkshop_entryRepository
from src.infrastructure.in_memory_repositories import InMemoryEnvironmentRepository
from src.infrastructure.in_memory_repositories import InMemoryTextureRepository
from src.infrastructure.in_memory_repositories import InMemoryMoral_choiceRepository
from src.infrastructure.in_memory_repositories import InMemoryVoice_lineRepository
from src.infrastructure.in_memory_repositories import InMemoryFamineRepository
from src.infrastructure.in_memory_repositories import InMemorySession_dataRepository
from src.infrastructure.in_memory_repositories import InMemoryPatentRepository
from src.infrastructure.in_memory_repositories import InMemoryArchiveRepository
from src.infrastructure.in_memory_repositories import InMemoryConversion_rateRepository
from src.infrastructure.in_memory_repositories import InMemoryScriptureRepository
from src.infrastructure.in_memory_repositories import InMemorySpaceshipRepository
from src.infrastructure.in_memory_repositories import InMemoryBattalionRepository
from src.infrastructure.in_memory_repositories import InMemoryPhenomenonRepository
from src.infrastructure.in_memory_repositories import InMemoryCompetitionRepository
from src.infrastructure.in_memory_repositories import InMemoryPlagueRepository
from src.infrastructure.in_memory_repositories import InMemoryBlack_holeRepository
from src.infrastructure.in_memory_repositories import InMemoryWitnessRepository
from src.infrastructure.in_memory_repositories import InMemoryCursed_itemRepository
from src.infrastructure.in_memory_repositories import InMemoryTimelineRepository
from src.infrastructure.in_memory_repositories import InMemoryComponentRepository
from src.infrastructure.in_memory_repositories import InMemoryCutsceneRepository
from src.infrastructure.in_memory_repositories import InMemoryFaction_hierarchyRepository
from src.infrastructure.in_memory_repositories import InMemoryMusic_trackRepository
from src.infrastructure.in_memory_repositories import InMemoryTrapRepository
from src.infrastructure.in_memory_repositories import InMemoryCrimeRepository
from src.infrastructure.in_memory_repositories import InMemoryFood_chainRepository
from src.infrastructure.in_memory_repositories import InMemoryReproductionRepository
from src.infrastructure.in_memory_repositories import InMemoryRaidRepository
from src.infrastructure.in_memory_repositories import InMemoryFlowchartRepository
from src.infrastructure.in_memory_repositories import InMemoryScoreRepository
from src.infrastructure.in_memory_repositories import InMemoryHonorRepository
from src.infrastructure.in_memory_repositories import InMemoryStorylineRepository
from src.infrastructure.in_memory_repositories import InMemoryLevel_upRepository
from src.infrastructure.in_memory_repositories import InMemoryNebulaRepository
from src.infrastructure.in_memory_repositories import InMemoryCodex_entryRepository
from src.infrastructure.in_memory_repositories import InMemorySubtitleRepository
from src.infrastructure.in_memory_repositories import InMemoryDistrictRepository
from src.infrastructure.in_memory_repositories import InMemoryQuest_prerequisiteRepository
from src.infrastructure.in_memory_repositories import InMemoryMythical_armorRepository
from src.infrastructure.in_memory_repositories import InMemoryRitualRepository
from src.infrastructure.in_memory_repositories import InMemoryRed_herringRepository
from src.infrastructure.in_memory_repositories import InMemoryPetRepository
from src.infrastructure.in_memory_repositories import InMemoryAtmosphereRepository
from src.infrastructure.in_memory_repositories import InMemorySocketRepository
from src.infrastructure.in_memory_repositories import InMemoryFlashbackRepository
from src.infrastructure.in_memory_repositories import InMemoryBadgeRepository
from src.infrastructure.in_memory_repositories import InMemoryPlazaRepository
from src.infrastructure.in_memory_repositories import InMemoryMapRepository
from src.infrastructure.in_memory_repositories import InMemoryEraRepository
from src.infrastructure.in_memory_repositories import InMemoryTournamentRepository
from src.infrastructure.in_memory_repositories import InMemoryShare_codeRepository
from src.infrastructure.in_memory_repositories import InMemoryLocalizationRepository
from src.infrastructure.in_memory_repositories import InMemoryMarket_squareRepository
from src.infrastructure.in_memory_repositories import InMemoryResearch_centerRepository
from src.infrastructure.in_memory_repositories import InMemoryHeatmapRepository
from src.infrastructure.in_memory_repositories import InMemoryResearchRepository
from src.infrastructure.in_memory_repositories import InMemoryRumorRepository
from src.infrastructure.in_memory_repositories import InMemoryInventionRepository
from src.infrastructure.in_memory_repositories import InMemoryCamera_pathRepository
from src.infrastructure.in_memory_repositories import InMemoryEnigmaRepository
from src.infrastructure.in_memory_repositories import InMemoryChekhovs_gunRepository
from src.infrastructure.in_memory_repositories import InMemoryReputationRepository
from src.infrastructure.in_memory_repositories import InMemoryParticleRepository
from src.infrastructure.in_memory_repositories import InMemoryFaction_territoryRepository
from src.infrastructure.in_memory_repositories import InMemoryCharacter_evolutionRepository
from src.infrastructure.in_memory_repositories import InMemoryTeleporterRepository
from src.infrastructure.in_memory_repositories import InMemoryShopRepository
from src.infrastructure.in_memory_repositories import InMemoryArenaRepository
from src.infrastructure.in_memory_repositories import InMemoryCurrencyRepository
from src.infrastructure.in_memory_repositories import InMemoryExhibitionRepository
from src.infrastructure.in_memory_repositories import InMemoryMigrationRepository
from src.infrastructure.in_memory_repositories import InMemoryForeshadowingRepository
from src.infrastructure.in_memory_repositories import InMemorySkyboxRepository
from src.infrastructure.in_memory_repositories import InMemoryQuest_reward_tierRepository
from src.infrastructure.in_memory_repositories import InMemoryCharacterRepository
from src.infrastructure.in_memory_repositories import InMemoryEvolutionRepository
from src.infrastructure.in_memory_repositories import InMemoryHibernationRepository
from src.infrastructure.in_memory_repositories import InMemoryConsequenceRepository
from src.infrastructure.in_memory_repositories import InMemoryDivine_itemRepository
from src.infrastructure.in_memory_repositories import InMemoryEaster_eggRepository
from src.infrastructure.in_memory_repositories import InMemoryVehicleRepository
from src.infrastructure.in_memory_repositories import InMemoryWeapon_systemRepository
from src.infrastructure.in_memory_repositories import InMemoryPort_districtRepository
from src.infrastructure.in_memory_repositories import InMemoryLibraryRepository
from src.infrastructure.in_memory_repositories import InMemoryTokenboardRepository
from src.infrastructure.in_memory_repositories import InMemoryLightingRepository
from src.infrastructure.in_memory_repositories import InMemoryCheckpointRepository
from src.infrastructure.in_memory_repositories import InMemoryUniversityRepository
from src.infrastructure.in_memory_repositories import InMemoryTrophyRepository
from src.infrastructure.in_memory_repositories import InMemorySummonRepository
from src.infrastructure.in_memory_repositories import InMemoryKingdomRepository
from src.infrastructure.in_memory_repositories import InMemoryLawRepository
from src.infrastructure.in_memory_repositories import InMemoryTemplateRepository
from src.infrastructure.in_memory_repositories import InMemoryAchievementRepository
from src.infrastructure.in_memory_repositories import InMemoryTransitionRepository
from src.infrastructure.in_memory_repositories import InMemoryTaxRepository
from src.infrastructure.in_memory_repositories import InMemoryLawyerRepository
from src.infrastructure.in_memory_repositories import InMemoryQuest_giverRepository
from src.infrastructure.in_memory_repositories import InMemoryPriceRepository
from src.infrastructure.in_memory_repositories import InMemoryEndingRepository
from src.infrastructure.in_memory_repositories import InMemoryPortalRepository
from src.infrastructure.in_memory_repositories import InMemoryTradeRepository
from src.infrastructure.in_memory_repositories import InMemoryOathRepository
from src.infrastructure.in_memory_repositories import InMemoryAmbientRepository
from src.infrastructure.in_memory_repositories import InMemoryMoonRepository
from src.infrastructure.in_memory_repositories import InMemoryExtinctionRepository
from src.infrastructure.in_memory_repositories import InMemoryDungeonRepository
from src.infrastructure.in_memory_repositories import InMemoryJournal_pageRepository
from src.infrastructure.in_memory_repositories import InMemoryGalaxyRepository
from src.infrastructure.in_memory_repositories import InMemoryPlayer_profileRepository
from src.infrastructure.in_memory_repositories import InMemoryNoble_districtRepository
from src.infrastructure.in_memory_repositories import InMemoryDispositionRepository
from src.infrastructure.in_memory_repositories import InMemoryJuryRepository
from src.infrastructure.in_memory_repositories import InMemoryCeremonyRepository
from src.infrastructure.sqlite_repositories import SQLiteMiracleRepository
from src.infrastructure.sqlite_repositories import SQLiteCourtRepository
from src.infrastructure.sqlite_repositories import SQLiteVoice_overRepository
from src.infrastructure.sqlite_repositories import SQLiteFestivalRepository
from src.infrastructure.sqlite_repositories import SQLiteCataclysmRepository
from src.infrastructure.sqlite_repositories import SQLiteProgression_stateRepository
from src.infrastructure.sqlite_repositories import SQLiteChapterRepository
from src.infrastructure.sqlite_repositories import SQLiteAttributeRepository
from src.infrastructure.sqlite_repositories import SQLiteNationRepository
from src.infrastructure.sqlite_repositories import SQLiteStoryRepository
from src.infrastructure.sqlite_repositories import SQLiteEvidenceRepository
from src.infrastructure.sqlite_repositories import SQLiteImprovementRepository
from src.infrastructure.sqlite_repositories import SQLiteLore_fragmentRepository
from src.infrastructure.sqlite_repositories import SQLiteFactionRepository
from src.infrastructure.sqlite_repositories import SQLiteConcertRepository
from src.infrastructure.sqlite_repositories import SQLiteAllianceRepository
from src.infrastructure.sqlite_repositories import SQLiteSkillRepository
from src.infrastructure.sqlite_repositories import SQLiteCinematicRepository
from src.infrastructure.sqlite_repositories import SQLiteDemandRepository
from src.infrastructure.sqlite_repositories import SQLiteNoteRepository
from src.infrastructure.sqlite_repositories import SQLiteDeus_ex_machinaRepository
from src.infrastructure.sqlite_repositories import SQLiteSeasonRepository
from src.infrastructure.sqlite_repositories import SQLiteFlash_forwardRepository
from src.infrastructure.sqlite_repositories import SQLiteWorldRepository
from src.infrastructure.sqlite_repositories import SQLiteTalent_treeRepository
from src.infrastructure.sqlite_repositories import SQLiteQuestRepository
from src.infrastructure.sqlite_repositories import SQLiteLegendary_weaponRepository
from src.infrastructure.sqlite_repositories import SQLiteGlyphRepository
from src.infrastructure.sqlite_repositories import SQLiteRelic_collectionRepository
from src.infrastructure.sqlite_repositories import SQLiteArtifact_setRepository
from src.infrastructure.sqlite_repositories import SQLiteDifficulty_curveRepository
from src.infrastructure.sqlite_repositories import SQLiteRequirementRepository
from src.infrastructure.sqlite_repositories import SQLitePlot_deviceRepository
from src.infrastructure.sqlite_repositories import SQLiteBannerRepository
from src.infrastructure.sqlite_repositories import SQLiteQuest_rewardRepository
from src.infrastructure.sqlite_repositories import SQLiteJudgeRepository
from src.infrastructure.sqlite_repositories import SQLiteNightmareRepository
from src.infrastructure.sqlite_repositories import SQLiteSecret_areaRepository
from src.infrastructure.sqlite_repositories import SQLitePactRepository
from src.infrastructure.sqlite_repositories import SQLiteWarRepository
from src.infrastructure.sqlite_repositories import SQLiteUser_scenarioRepository
from src.infrastructure.sqlite_repositories import SQLiteVisual_effectRepository
from src.infrastructure.sqlite_repositories import SQLiteMaterialRepository
from src.infrastructure.sqlite_repositories import SQLiteSave_pointRepository
from src.infrastructure.sqlite_repositories import SQLitePropagandaRepository
from src.infrastructure.sqlite_repositories import SQLiteLeaderboardRepository
from src.infrastructure.sqlite_repositories import SQLiteEclipseRepository
from src.infrastructure.sqlite_repositories import SQLiteBalance_entitiesRepository
from src.infrastructure.sqlite_repositories import SQLitePunishmentRepository
from src.infrastructure.sqlite_repositories import SQLiteUndergroundRepository
from src.infrastructure.sqlite_repositories import SQLiteRadioRepository
from src.infrastructure.sqlite_repositories import SQLiteBestiary_entryRepository
from src.infrastructure.sqlite_repositories import SQLiteOpen_world_zoneRepository
from src.infrastructure.sqlite_repositories import SQLiteRewardRepository
from src.infrastructure.sqlite_repositories import SQLiteDrop_rateRepository
from src.infrastructure.sqlite_repositories import SQLiteMusic_themeRepository
from src.infrastructure.sqlite_repositories import SQLiteConstitutionRepository
from src.infrastructure.sqlite_repositories import SQLiteDefenseRepository
from src.infrastructure.sqlite_repositories import SQLiteInvasionRepository
from src.infrastructure.sqlite_repositories import SQLiteInspirationRepository
from src.infrastructure.sqlite_repositories import SQLiteLoot_table_weightRepository
from src.infrastructure.sqlite_repositories import SQLiteDiscoveryRepository
from src.infrastructure.sqlite_repositories import SQLiteMountRepository
from src.infrastructure.sqlite_repositories import SQLiteWormholeRepository
from src.infrastructure.sqlite_repositories import SQLitePocket_dimensionRepository
from src.infrastructure.sqlite_repositories import SQLiteEvent_chainRepository
from src.infrastructure.sqlite_repositories import SQLitePrologueRepository
from src.infrastructure.sqlite_repositories import SQLiteFadeRepository
from src.infrastructure.sqlite_repositories import SQLiteAutosaveRepository
from src.infrastructure.sqlite_repositories import SQLitePerkRepository
from src.infrastructure.sqlite_repositories import SQLiteSocial_mobilityRepository
from src.infrastructure.sqlite_repositories import SQLiteCharacter_profile_entryRepository
from src.infrastructure.sqlite_repositories import SQLiteModel3dRepository
from src.infrastructure.sqlite_repositories import SQLiteSoundtrackRepository
from src.infrastructure.sqlite_repositories import SQLiteTagRepository
from src.infrastructure.sqlite_repositories import SQLiteInflationRepository
from src.infrastructure.sqlite_repositories import SQLiteStar_systemRepository
from src.infrastructure.sqlite_repositories import SQLiteQuarterRepository
from src.infrastructure.sqlite_repositories import SQLitePurchaseRepository
from src.infrastructure.sqlite_repositories import SQLiteCharacter_relationshipRepository
from src.infrastructure.sqlite_repositories import SQLiteGovernmentRepository
from src.infrastructure.sqlite_repositories import SQLiteCampaignRepository
from src.infrastructure.sqlite_repositories import SQLiteEventRepository
from src.infrastructure.sqlite_repositories import SQLitePityRepository
from src.infrastructure.sqlite_repositories import SQLiteImageRepository
from src.infrastructure.sqlite_repositories import SQLiteTranslationRepository
from src.infrastructure.sqlite_repositories import SQLiteColor_paletteRepository
from src.infrastructure.sqlite_repositories import SQLiteSeasonal_eventRepository
from src.infrastructure.sqlite_repositories import SQLiteArmyRepository
from src.infrastructure.sqlite_repositories import SQLiteModRepository
from src.infrastructure.sqlite_repositories import SQLiteBlueprintRepository
from src.infrastructure.sqlite_repositories import SQLiteQuest_trackerRepository
from src.infrastructure.sqlite_repositories import SQLiteRankRepository
from src.infrastructure.sqlite_repositories import SQLiteCelebrationRepository
from src.infrastructure.sqlite_repositories import SQLiteItemRepository
from src.infrastructure.sqlite_repositories import SQLiteCurseRepository
from src.infrastructure.sqlite_repositories import SQLiteHub_areaRepository
from src.infrastructure.sqlite_repositories import SQLiteLocationRepository
from src.infrastructure.sqlite_repositories import SQLiteRevolutionRepository
from src.infrastructure.sqlite_repositories import SQLiteFaction_resourceRepository
from src.infrastructure.sqlite_repositories import SQLiteTreatyRepository
from src.infrastructure.sqlite_repositories import SQLiteAirshipRepository
from src.infrastructure.sqlite_repositories import SQLiteCultRepository
from src.infrastructure.sqlite_repositories import SQLiteEnchantmentRepository
from src.infrastructure.sqlite_repositories import SQLiteInstanceRepository
from src.infrastructure.sqlite_repositories import SQLiteAcademyRepository
from src.infrastructure.sqlite_repositories import SQLiteSilenceRepository
from src.infrastructure.sqlite_repositories import SQLiteLore_axiomsRepository
from src.infrastructure.sqlite_repositories import SQLiteSupplyRepository
from src.infrastructure.sqlite_repositories import SQLiteFaction_membershipRepository
from src.infrastructure.sqlite_repositories import SQLiteMusic_stateRepository
from src.infrastructure.sqlite_repositories import SQLiteBlessingRepository
from src.infrastructure.sqlite_repositories import SQLitePrototypeRepository
from src.infrastructure.sqlite_repositories import SQLiteFaction_ideologyRepository
from src.infrastructure.sqlite_repositories import SQLiteKarmaRepository
from src.infrastructure.sqlite_repositories import SQLiteCharacter_variantRepository
from src.infrastructure.sqlite_repositories import SQLiteLegal_systemRepository
from src.infrastructure.sqlite_repositories import SQLiteQuest_objectiveRepository
from src.infrastructure.sqlite_repositories import SQLitePlot_branchRepository
from src.infrastructure.sqlite_repositories import SQLiteWaypointRepository
from src.infrastructure.sqlite_repositories import SQLiteProgression_eventRepository
from src.infrastructure.sqlite_repositories import SQLiteNewspaperRepository
from src.infrastructure.sqlite_repositories import SQLiteWardRepository
from src.infrastructure.sqlite_repositories import SQLiteMemoryRepository
from src.infrastructure.sqlite_repositories import SQLitePullRepository
from src.infrastructure.sqlite_repositories import SQLiteHandoutRepository
from src.infrastructure.sqlite_repositories import SQLiteBranch_pointRepository
from src.infrastructure.sqlite_repositories import SQLiteWorld_eventRepository
from src.infrastructure.sqlite_repositories import SQLiteSectRepository
from src.infrastructure.sqlite_repositories import SQLiteEmpireRepository
from src.infrastructure.sqlite_repositories import SQLiteQuest_chainRepository
from src.infrastructure.sqlite_repositories import SQLiteChoiceRepository
from src.infrastructure.sqlite_repositories import SQLiteRuneRepository
from src.infrastructure.sqlite_repositories import SQLiteHolidayRepository
from src.infrastructure.sqlite_repositories import SQLiteShaderRepository
from src.infrastructure.sqlite_repositories import SQLiteTitleRepository
from src.infrastructure.sqlite_repositories import SQLitePlayer_metricRepository
from src.infrastructure.sqlite_repositories import SQLiteEpilogueRepository
from src.infrastructure.sqlite_repositories import SQLiteMysteryRepository
from src.infrastructure.sqlite_repositories import SQLiteWeather_patternRepository
from src.infrastructure.sqlite_repositories import SQLiteActRepository
from src.infrastructure.sqlite_repositories import SQLiteEpisodeRepository
from src.infrastructure.sqlite_repositories import SQLiteTelevisionRepository
from src.infrastructure.sqlite_repositories import SQLiteSiege_engineRepository
from src.infrastructure.sqlite_repositories import SQLiteCustom_mapRepository
from src.infrastructure.sqlite_repositories import SQLiteThemeRepository
from src.infrastructure.sqlite_repositories import SQLiteCrafting_recipeRepository
from src.infrastructure.sqlite_repositories import SQLiteSocial_classRepository
from src.infrastructure.sqlite_repositories import SQLiteFaction_leaderRepository
from src.infrastructure.sqlite_repositories import SQLiteRiddleRepository
from src.infrastructure.sqlite_repositories import SQLiteFast_travel_pointRepository
from src.infrastructure.sqlite_repositories import SQLiteMuseumRepository
from src.infrastructure.sqlite_repositories import SQLiteTraitRepository
from src.infrastructure.sqlite_repositories import SQLiteFamiliarRepository
from src.infrastructure.sqlite_repositories import SQLiteEra_transitionRepository
from src.infrastructure.sqlite_repositories import SQLiteTariffRepository
from src.infrastructure.sqlite_repositories import SQLiteQuest_nodeRepository
from src.infrastructure.sqlite_repositories import SQLiteDreamRepository
from src.infrastructure.sqlite_repositories import SQLiteHoly_siteRepository
from src.infrastructure.sqlite_repositories import SQLiteInventoryRepository
from src.infrastructure.sqlite_repositories import SQLiteAffinityRepository
from src.infrastructure.sqlite_repositories import SQLiteAlternate_realityRepository
from src.infrastructure.sqlite_repositories import SQLiteMount_equipmentRepository
from src.infrastructure.sqlite_repositories import SQLiteSound_effectRepository
from src.infrastructure.sqlite_repositories import SQLiteInternetRepository
from src.infrastructure.sqlite_repositories import SQLiteTime_periodRepository
from src.infrastructure.sqlite_repositories import SQLiteSessionRepository
from src.infrastructure.sqlite_repositories import SQLiteExperienceRepository
from src.infrastructure.sqlite_repositories import SQLitePuzzleRepository
from src.infrastructure.sqlite_repositories import SQLiteMotion_captureRepository
from src.infrastructure.sqlite_repositories import SQLiteFortificationRepository
from src.infrastructure.sqlite_repositories import SQLiteVoice_actorRepository
from src.infrastructure.sqlite_repositories import SQLiteDimensionRepository
from src.infrastructure.sqlite_repositories import SQLiteMusic_controlRepository
from src.infrastructure.sqlite_repositories import SQLiteDubbingRepository
from src.infrastructure.sqlite_repositories import SQLiteHidden_pathRepository
from src.infrastructure.sqlite_repositories import SQLiteFleetRepository
from src.infrastructure.sqlite_repositories import SQLiteSocial_mediaRepository
from src.infrastructure.sqlite_repositories import SQLiteBarterRepository
from src.infrastructure.sqlite_repositories import SQLiteCalendarRepository
from src.infrastructure.sqlite_repositories import SQLiteSolsticeRepository
from src.infrastructure.sqlite_repositories import SQLiteSchoolRepository
from src.infrastructure.sqlite_repositories import SQLiteSlumsRepository
from src.infrastructure.sqlite_repositories import SQLiteDisasterRepository
from src.infrastructure.sqlite_repositories import SQLiteMasteryRepository
from src.infrastructure.sqlite_repositories import SQLitePageRepository
from src.infrastructure.sqlite_repositories import SQLiteMotifRepository
from src.infrastructure.sqlite_repositories import SQLiteSpawn_pointRepository
from src.infrastructure.sqlite_repositories import SQLiteWorkshop_entryRepository
from src.infrastructure.sqlite_repositories import SQLiteEnvironmentRepository
from src.infrastructure.sqlite_repositories import SQLiteTextureRepository
from src.infrastructure.sqlite_repositories import SQLiteMoral_choiceRepository
from src.infrastructure.sqlite_repositories import SQLiteVoice_lineRepository
from src.infrastructure.sqlite_repositories import SQLiteFamineRepository
from src.infrastructure.sqlite_repositories import SQLiteSession_dataRepository
from src.infrastructure.sqlite_repositories import SQLitePatentRepository
from src.infrastructure.sqlite_repositories import SQLiteArchiveRepository
from src.infrastructure.sqlite_repositories import SQLiteConversion_rateRepository
from src.infrastructure.sqlite_repositories import SQLiteScriptureRepository
from src.infrastructure.sqlite_repositories import SQLiteSpaceshipRepository
from src.infrastructure.sqlite_repositories import SQLiteBattalionRepository
from src.infrastructure.sqlite_repositories import SQLitePhenomenonRepository
from src.infrastructure.sqlite_repositories import SQLiteCompetitionRepository
from src.infrastructure.sqlite_repositories import SQLitePlagueRepository
from src.infrastructure.sqlite_repositories import SQLiteBlack_holeRepository
from src.infrastructure.sqlite_repositories import SQLiteWitnessRepository
from src.infrastructure.sqlite_repositories import SQLiteCursed_itemRepository
from src.infrastructure.sqlite_repositories import SQLiteTimelineRepository
from src.infrastructure.sqlite_repositories import SQLiteComponentRepository
from src.infrastructure.sqlite_repositories import SQLiteCutsceneRepository
from src.infrastructure.sqlite_repositories import SQLiteFaction_hierarchyRepository
from src.infrastructure.sqlite_repositories import SQLiteMusic_trackRepository
from src.infrastructure.sqlite_repositories import SQLiteTrapRepository
from src.infrastructure.sqlite_repositories import SQLiteCrimeRepository
from src.infrastructure.sqlite_repositories import SQLiteFood_chainRepository
from src.infrastructure.sqlite_repositories import SQLiteReproductionRepository
from src.infrastructure.sqlite_repositories import SQLiteRaidRepository
from src.infrastructure.sqlite_repositories import SQLiteFlowchartRepository
from src.infrastructure.sqlite_repositories import SQLiteScoreRepository
from src.infrastructure.sqlite_repositories import SQLiteHonorRepository
from src.infrastructure.sqlite_repositories import SQLiteStorylineRepository
from src.infrastructure.sqlite_repositories import SQLiteLevel_upRepository
from src.infrastructure.sqlite_repositories import SQLiteNebulaRepository
from src.infrastructure.sqlite_repositories import SQLiteCodex_entryRepository
from src.infrastructure.sqlite_repositories import SQLiteSubtitleRepository
from src.infrastructure.sqlite_repositories import SQLiteDistrictRepository
from src.infrastructure.sqlite_repositories import SQLiteQuest_prerequisiteRepository
from src.infrastructure.sqlite_repositories import SQLiteMythical_armorRepository
from src.infrastructure.sqlite_repositories import SQLiteRitualRepository
from src.infrastructure.sqlite_repositories import SQLiteRed_herringRepository
from src.infrastructure.sqlite_repositories import SQLitePetRepository
from src.infrastructure.sqlite_repositories import SQLiteAtmosphereRepository
from src.infrastructure.sqlite_repositories import SQLiteSocketRepository
from src.infrastructure.sqlite_repositories import SQLiteFlashbackRepository
from src.infrastructure.sqlite_repositories import SQLiteBadgeRepository
from src.infrastructure.sqlite_repositories import SQLitePlazaRepository
from src.infrastructure.sqlite_repositories import SQLiteMapRepository
from src.infrastructure.sqlite_repositories import SQLiteEraRepository
from src.infrastructure.sqlite_repositories import SQLiteTournamentRepository
from src.infrastructure.sqlite_repositories import SQLiteShare_codeRepository
from src.infrastructure.sqlite_repositories import SQLiteLocalizationRepository
from src.infrastructure.sqlite_repositories import SQLiteMarket_squareRepository
from src.infrastructure.sqlite_repositories import SQLiteResearch_centerRepository
from src.infrastructure.sqlite_repositories import SQLiteHeatmapRepository
from src.infrastructure.sqlite_repositories import SQLiteResearchRepository
from src.infrastructure.sqlite_repositories import SQLiteRumorRepository
from src.infrastructure.sqlite_repositories import SQLiteInventionRepository
from src.infrastructure.sqlite_repositories import SQLiteCamera_pathRepository
from src.infrastructure.sqlite_repositories import SQLiteEnigmaRepository
from src.infrastructure.sqlite_repositories import SQLiteChekhovs_gunRepository
from src.infrastructure.sqlite_repositories import SQLiteReputationRepository
from src.infrastructure.sqlite_repositories import SQLiteParticleRepository
from src.infrastructure.sqlite_repositories import SQLiteFaction_territoryRepository
from src.infrastructure.sqlite_repositories import SQLiteCharacter_evolutionRepository
from src.infrastructure.sqlite_repositories import SQLiteTeleporterRepository
from src.infrastructure.sqlite_repositories import SQLiteShopRepository
from src.infrastructure.sqlite_repositories import SQLiteArenaRepository
from src.infrastructure.sqlite_repositories import SQLiteCurrencyRepository
from src.infrastructure.sqlite_repositories import SQLiteExhibitionRepository
from src.infrastructure.sqlite_repositories import SQLiteMigrationRepository
from src.infrastructure.sqlite_repositories import SQLiteForeshadowingRepository
from src.infrastructure.sqlite_repositories import SQLiteSkyboxRepository
from src.infrastructure.sqlite_repositories import SQLiteQuest_reward_tierRepository
from src.infrastructure.sqlite_repositories import SQLiteCharacterRepository
from src.infrastructure.sqlite_repositories import SQLiteEvolutionRepository
from src.infrastructure.sqlite_repositories import SQLiteHibernationRepository
from src.infrastructure.sqlite_repositories import SQLiteConsequenceRepository
from src.infrastructure.sqlite_repositories import SQLiteDivine_itemRepository
from src.infrastructure.sqlite_repositories import SQLiteEaster_eggRepository
from src.infrastructure.sqlite_repositories import SQLiteVehicleRepository
from src.infrastructure.sqlite_repositories import SQLiteWeapon_systemRepository
from src.infrastructure.sqlite_repositories import SQLitePort_districtRepository
from src.infrastructure.sqlite_repositories import SQLiteLibraryRepository
from src.infrastructure.sqlite_repositories import SQLiteTokenboardRepository
from src.infrastructure.sqlite_repositories import SQLiteLightingRepository
from src.infrastructure.sqlite_repositories import SQLiteCheckpointRepository
from src.infrastructure.sqlite_repositories import SQLiteUniversityRepository
from src.infrastructure.sqlite_repositories import SQLiteTrophyRepository
from src.infrastructure.sqlite_repositories import SQLiteSummonRepository
from src.infrastructure.sqlite_repositories import SQLiteKingdomRepository
from src.infrastructure.sqlite_repositories import SQLiteLawRepository
from src.infrastructure.sqlite_repositories import SQLiteTemplateRepository
from src.infrastructure.sqlite_repositories import SQLiteAchievementRepository
from src.infrastructure.sqlite_repositories import SQLiteTransitionRepository
from src.infrastructure.sqlite_repositories import SQLiteTaxRepository
from src.infrastructure.sqlite_repositories import SQLiteLawyerRepository
from src.infrastructure.sqlite_repositories import SQLiteQuest_giverRepository
from src.infrastructure.sqlite_repositories import SQLitePriceRepository
from src.infrastructure.sqlite_repositories import SQLiteEndingRepository
from src.infrastructure.sqlite_repositories import SQLitePortalRepository
from src.infrastructure.sqlite_repositories import SQLiteTradeRepository
from src.infrastructure.sqlite_repositories import SQLiteOathRepository
from src.infrastructure.sqlite_repositories import SQLiteAmbientRepository
from src.infrastructure.sqlite_repositories import SQLiteMoonRepository
from src.infrastructure.sqlite_repositories import SQLiteExtinctionRepository
from src.infrastructure.sqlite_repositories import SQLiteDungeonRepository
from src.infrastructure.sqlite_repositories import SQLiteJournal_pageRepository
from src.infrastructure.sqlite_repositories import SQLiteGalaxyRepository
from src.infrastructure.sqlite_repositories import SQLitePlayer_profileRepository
from src.infrastructure.sqlite_repositories import SQLiteNoble_districtRepository
from src.infrastructure.sqlite_repositories import SQLiteDispositionRepository
from src.infrastructure.sqlite_repositories import SQLiteJuryRepository
from src.infrastructure.sqlite_repositories import SQLiteCeremonyRepository

# All repositories
    'InMemoryMiracleRepository',
    'InMemoryCourtRepository',
    'InMemoryVoice_overRepository',
    'InMemoryFestivalRepository',
    'InMemoryCataclysmRepository',
    'InMemoryProgression_stateRepository',
    'InMemoryChapterRepository',
    'InMemoryAttributeRepository',
    'InMemoryNationRepository',
    'InMemoryStoryRepository',
    'InMemoryEvidenceRepository',
    'InMemoryImprovementRepository',
    'InMemoryLore_fragmentRepository',
    'InMemoryFactionRepository',
    'InMemoryConcertRepository',
    'InMemoryAllianceRepository',
    'InMemorySkillRepository',
    'InMemoryCinematicRepository',
    'InMemoryDemandRepository',
    'InMemoryNoteRepository',
    'InMemoryDeus_ex_machinaRepository',
    'InMemorySeasonRepository',
    'InMemoryFlash_forwardRepository',
    'InMemoryWorldRepository',
    'InMemoryTalent_treeRepository',
    'InMemoryQuestRepository',
    'InMemoryLegendary_weaponRepository',
    'InMemoryGlyphRepository',
    'InMemoryRelic_collectionRepository',
    'InMemoryArtifact_setRepository',
    'InMemoryDifficulty_curveRepository',
    'InMemoryRequirementRepository',
    'InMemoryPlot_deviceRepository',
    'InMemoryBannerRepository',
    'InMemoryQuest_rewardRepository',
    'InMemoryJudgeRepository',
    'InMemoryNightmareRepository',
    'InMemorySecret_areaRepository',
    'InMemoryPactRepository',
    'InMemoryWarRepository',
    'InMemoryUser_scenarioRepository',
    'InMemoryVisual_effectRepository',
    'InMemoryMaterialRepository',
    'InMemorySave_pointRepository',
    'InMemoryPropagandaRepository',
    'InMemoryLeaderboardRepository',
    'InMemoryEclipseRepository',
    'InMemoryBalance_entitiesRepository',
    'InMemoryPunishmentRepository',
    'InMemoryUndergroundRepository',
    'InMemoryRadioRepository',
    'InMemoryBestiary_entryRepository',
    'InMemoryOpen_world_zoneRepository',
    'InMemoryRewardRepository',
    'InMemoryDrop_rateRepository',
    'InMemoryMusic_themeRepository',
    'InMemoryConstitutionRepository',
    'InMemoryDefenseRepository',
    'InMemoryInvasionRepository',
    'InMemoryInspirationRepository',
    'InMemoryLoot_table_weightRepository',
    'InMemoryDiscoveryRepository',
    'InMemoryMountRepository',
    'InMemoryWormholeRepository',
    'InMemoryPocket_dimensionRepository',
    'InMemoryEvent_chainRepository',
    'InMemoryPrologueRepository',
    'InMemoryFadeRepository',
    'InMemoryAutosaveRepository',
    'InMemoryPerkRepository',
    'InMemorySocial_mobilityRepository',
    'InMemoryCharacter_profile_entryRepository',
    'InMemoryModel3dRepository',
    'InMemorySoundtrackRepository',
    'InMemoryTagRepository',
    'InMemoryInflationRepository',
    'InMemoryStar_systemRepository',
    'InMemoryQuarterRepository',
    'InMemoryPurchaseRepository',
    'InMemoryCharacter_relationshipRepository',
    'InMemoryGovernmentRepository',
    'InMemoryCampaignRepository',
    'InMemoryEventRepository',
    'InMemoryPityRepository',
    'InMemoryImageRepository',
    'InMemoryTranslationRepository',
    'InMemoryColor_paletteRepository',
    'InMemorySeasonal_eventRepository',
    'InMemoryArmyRepository',
    'InMemoryModRepository',
    'InMemoryBlueprintRepository',
    'InMemoryQuest_trackerRepository',
    'InMemoryRankRepository',
    'InMemoryCelebrationRepository',
    'InMemoryItemRepository',
    'InMemoryCurseRepository',
    'InMemoryHub_areaRepository',
    'InMemoryLocationRepository',
    'InMemoryRevolutionRepository',
    'InMemoryFaction_resourceRepository',
    'InMemoryTreatyRepository',
    'InMemoryAirshipRepository',
    'InMemoryCultRepository',
    'InMemoryEnchantmentRepository',
    'InMemoryInstanceRepository',
    'InMemoryAcademyRepository',
    'InMemorySilenceRepository',
    'InMemoryLore_axiomsRepository',
    'InMemorySupplyRepository',
    'InMemoryFaction_membershipRepository',
    'InMemoryMusic_stateRepository',
    'InMemoryBlessingRepository',
    'InMemoryPrototypeRepository',
    'InMemoryFaction_ideologyRepository',
    'InMemoryKarmaRepository',
    'InMemoryCharacter_variantRepository',
    'InMemoryLegal_systemRepository',
    'InMemoryQuest_objectiveRepository',
    'InMemoryPlot_branchRepository',
    'InMemoryWaypointRepository',
    'InMemoryProgression_eventRepository',
    'InMemoryNewspaperRepository',
    'InMemoryWardRepository',
    'InMemoryMemoryRepository',
    'InMemoryPullRepository',
    'InMemoryHandoutRepository',
    'InMemoryBranch_pointRepository',
    'InMemoryWorld_eventRepository',
    'InMemorySectRepository',
    'InMemoryEmpireRepository',
    'InMemoryQuest_chainRepository',
    'InMemoryChoiceRepository',
    'InMemoryRuneRepository',
    'InMemoryHolidayRepository',
    'InMemoryShaderRepository',
    'InMemoryTitleRepository',
    'InMemoryPlayer_metricRepository',
    'InMemoryEpilogueRepository',
    'InMemoryMysteryRepository',
    'InMemoryWeather_patternRepository',
    'InMemoryActRepository',
    'InMemoryEpisodeRepository',
    'InMemoryTelevisionRepository',
    'InMemorySiege_engineRepository',
    'InMemoryCustom_mapRepository',
    'InMemoryThemeRepository',
    'InMemoryCrafting_recipeRepository',
    'InMemorySocial_classRepository',
    'InMemoryFaction_leaderRepository',
    'InMemoryRiddleRepository',
    'InMemoryFast_travel_pointRepository',
    'InMemoryMuseumRepository',
    'InMemoryTraitRepository',
    'InMemoryFamiliarRepository',
    'InMemoryEra_transitionRepository',
    'InMemoryTariffRepository',
    'InMemoryQuest_nodeRepository',
    'InMemoryDreamRepository',
    'InMemoryHoly_siteRepository',
    'InMemoryInventoryRepository',
    'InMemoryAffinityRepository',
    'InMemoryAlternate_realityRepository',
    'InMemoryMount_equipmentRepository',
    'InMemorySound_effectRepository',
    'InMemoryInternetRepository',
    'InMemoryTime_periodRepository',
    'InMemorySessionRepository',
    'InMemoryExperienceRepository',
    'InMemoryPuzzleRepository',
    'InMemoryMotion_captureRepository',
    'InMemoryFortificationRepository',
    'InMemoryVoice_actorRepository',
    'InMemoryDimensionRepository',
    'InMemoryMusic_controlRepository',
    'InMemoryDubbingRepository',
    'InMemoryHidden_pathRepository',
    'InMemoryFleetRepository',
    'InMemorySocial_mediaRepository',
    'InMemoryBarterRepository',
    'InMemoryCalendarRepository',
    'InMemorySolsticeRepository',
    'InMemorySchoolRepository',
    'InMemorySlumsRepository',
    'InMemoryDisasterRepository',
    'InMemoryMasteryRepository',
    'InMemoryPageRepository',
    'InMemoryMotifRepository',
    'InMemorySpawn_pointRepository',
    'InMemoryWorkshop_entryRepository',
    'InMemoryEnvironmentRepository',
    'InMemoryTextureRepository',
    'InMemoryMoral_choiceRepository',
    'InMemoryVoice_lineRepository',
    'InMemoryFamineRepository',
    'InMemorySession_dataRepository',
    'InMemoryPatentRepository',
    'InMemoryArchiveRepository',
    'InMemoryConversion_rateRepository',
    'InMemoryScriptureRepository',
    'InMemorySpaceshipRepository',
    'InMemoryBattalionRepository',
    'InMemoryPhenomenonRepository',
    'InMemoryCompetitionRepository',
    'InMemoryPlagueRepository',
    'InMemoryBlack_holeRepository',
    'InMemoryWitnessRepository',
    'InMemoryCursed_itemRepository',
    'InMemoryTimelineRepository',
    'InMemoryComponentRepository',
    'InMemoryCutsceneRepository',
    'InMemoryFaction_hierarchyRepository',
    'InMemoryMusic_trackRepository',
    'InMemoryTrapRepository',
    'InMemoryCrimeRepository',
    'InMemoryFood_chainRepository',
    'InMemoryReproductionRepository',
    'InMemoryRaidRepository',
    'InMemoryFlowchartRepository',
    'InMemoryScoreRepository',
    'InMemoryHonorRepository',
    'InMemoryStorylineRepository',
    'InMemoryLevel_upRepository',
    'InMemoryNebulaRepository',
    'InMemoryCodex_entryRepository',
    'InMemorySubtitleRepository',
    'InMemoryDistrictRepository',
    'InMemoryQuest_prerequisiteRepository',
    'InMemoryMythical_armorRepository',
    'InMemoryRitualRepository',
    'InMemoryRed_herringRepository',
    'InMemoryPetRepository',
    'InMemoryAtmosphereRepository',
    'InMemorySocketRepository',
    'InMemoryFlashbackRepository',
    'InMemoryBadgeRepository',
    'InMemoryPlazaRepository',
    'InMemoryMapRepository',
    'InMemoryEraRepository',
    'InMemoryTournamentRepository',
    'InMemoryShare_codeRepository',
    'InMemoryLocalizationRepository',
    'InMemoryMarket_squareRepository',
    'InMemoryResearch_centerRepository',
    'InMemoryHeatmapRepository',
    'InMemoryResearchRepository',
    'InMemoryRumorRepository',
    'InMemoryInventionRepository',
    'InMemoryCamera_pathRepository',
    'InMemoryEnigmaRepository',
    'InMemoryChekhovs_gunRepository',
    'InMemoryReputationRepository',
    'InMemoryParticleRepository',
    'InMemoryFaction_territoryRepository',
    'InMemoryCharacter_evolutionRepository',
    'InMemoryTeleporterRepository',
    'InMemoryShopRepository',
    'InMemoryArenaRepository',
    'InMemoryCurrencyRepository',
    'InMemoryExhibitionRepository',
    'InMemoryMigrationRepository',
    'InMemoryForeshadowingRepository',
    'InMemorySkyboxRepository',
    'InMemoryQuest_reward_tierRepository',
    'InMemoryCharacterRepository',
    'InMemoryEvolutionRepository',
    'InMemoryHibernationRepository',
    'InMemoryConsequenceRepository',
    'InMemoryDivine_itemRepository',
    'InMemoryEaster_eggRepository',
    'InMemoryVehicleRepository',
    'InMemoryWeapon_systemRepository',
    'InMemoryPort_districtRepository',
    'InMemoryLibraryRepository',
    'InMemoryTokenboardRepository',
    'InMemoryLightingRepository',
    'InMemoryCheckpointRepository',
    'InMemoryUniversityRepository',
    'InMemoryTrophyRepository',
    'InMemorySummonRepository',
    'InMemoryKingdomRepository',
    'InMemoryLawRepository',
    'InMemoryTemplateRepository',
    'InMemoryAchievementRepository',
    'InMemoryTransitionRepository',
    'InMemoryTaxRepository',
    'InMemoryLawyerRepository',
    'InMemoryQuest_giverRepository',
    'InMemoryPriceRepository',
    'InMemoryEndingRepository',
    'InMemoryPortalRepository',
    'InMemoryTradeRepository',
    'InMemoryOathRepository',
    'InMemoryAmbientRepository',
    'InMemoryMoonRepository',
    'InMemoryExtinctionRepository',
    'InMemoryDungeonRepository',
    'InMemoryJournal_pageRepository',
    'InMemoryGalaxyRepository',
    'InMemoryPlayer_profileRepository',
    'InMemoryNoble_districtRepository',
    'InMemoryDispositionRepository',
    'InMemoryJuryRepository',
    'InMemoryCeremonyRepository',
    'SQLiteMiracleRepository',
    'SQLiteCourtRepository',
    'SQLiteVoice_overRepository',
    'SQLiteFestivalRepository',
    'SQLiteCataclysmRepository',
    'SQLiteProgression_stateRepository',
    'SQLiteChapterRepository',
    'SQLiteAttributeRepository',
    'SQLiteNationRepository',
    'SQLiteStoryRepository',
    'SQLiteEvidenceRepository',
    'SQLiteImprovementRepository',
    'SQLiteLore_fragmentRepository',
    'SQLiteFactionRepository',
    'SQLiteConcertRepository',
    'SQLiteAllianceRepository',
    'SQLiteSkillRepository',
    'SQLiteCinematicRepository',
    'SQLiteDemandRepository',
    'SQLiteNoteRepository',
    'SQLiteDeus_ex_machinaRepository',
    'SQLiteSeasonRepository',
    'SQLiteFlash_forwardRepository',
    'SQLiteWorldRepository',
    'SQLiteTalent_treeRepository',
    'SQLiteQuestRepository',
    'SQLiteLegendary_weaponRepository',
    'SQLiteGlyphRepository',
    'SQLiteRelic_collectionRepository',
    'SQLiteArtifact_setRepository',
    'SQLiteDifficulty_curveRepository',
    'SQLiteRequirementRepository',
    'SQLitePlot_deviceRepository',
    'SQLiteBannerRepository',
    'SQLiteQuest_rewardRepository',
    'SQLiteJudgeRepository',
    'SQLiteNightmareRepository',
    'SQLiteSecret_areaRepository',
    'SQLitePactRepository',
    'SQLiteWarRepository',
    'SQLiteUser_scenarioRepository',
    'SQLiteVisual_effectRepository',
    'SQLiteMaterialRepository',
    'SQLiteSave_pointRepository',
    'SQLitePropagandaRepository',
    'SQLiteLeaderboardRepository',
    'SQLiteEclipseRepository',
    'SQLiteBalance_entitiesRepository',
    'SQLitePunishmentRepository',
    'SQLiteUndergroundRepository',
    'SQLiteRadioRepository',
    'SQLiteBestiary_entryRepository',
    'SQLiteOpen_world_zoneRepository',
    'SQLiteRewardRepository',
    'SQLiteDrop_rateRepository',
    'SQLiteMusic_themeRepository',
    'SQLiteConstitutionRepository',
    'SQLiteDefenseRepository',
    'SQLiteInvasionRepository',
    'SQLiteInspirationRepository',
    'SQLiteLoot_table_weightRepository',
    'SQLiteDiscoveryRepository',
    'SQLiteMountRepository',
    'SQLiteWormholeRepository',
    'SQLitePocket_dimensionRepository',
    'SQLiteEvent_chainRepository',
    'SQLitePrologueRepository',
    'SQLiteFadeRepository',
    'SQLiteAutosaveRepository',
    'SQLitePerkRepository',
    'SQLiteSocial_mobilityRepository',
    'SQLiteCharacter_profile_entryRepository',
    'SQLiteModel3dRepository',
    'SQLiteSoundtrackRepository',
    'SQLiteTagRepository',
    'SQLiteInflationRepository',
    'SQLiteStar_systemRepository',
    'SQLiteQuarterRepository',
    'SQLitePurchaseRepository',
    'SQLiteCharacter_relationshipRepository',
    'SQLiteGovernmentRepository',
    'SQLiteCampaignRepository',
    'SQLiteEventRepository',
    'SQLitePityRepository',
    'SQLiteImageRepository',
    'SQLiteTranslationRepository',
    'SQLiteColor_paletteRepository',
    'SQLiteSeasonal_eventRepository',
    'SQLiteArmyRepository',
    'SQLiteModRepository',
    'SQLiteBlueprintRepository',
    'SQLiteQuest_trackerRepository',
    'SQLiteRankRepository',
    'SQLiteCelebrationRepository',
    'SQLiteItemRepository',
    'SQLiteCurseRepository',
    'SQLiteHub_areaRepository',
    'SQLiteLocationRepository',
    'SQLiteRevolutionRepository',
    'SQLiteFaction_resourceRepository',
    'SQLiteTreatyRepository',
    'SQLiteAirshipRepository',
    'SQLiteCultRepository',
    'SQLiteEnchantmentRepository',
    'SQLiteInstanceRepository',
    'SQLiteAcademyRepository',
    'SQLiteSilenceRepository',
    'SQLiteLore_axiomsRepository',
    'SQLiteSupplyRepository',
    'SQLiteFaction_membershipRepository',
    'SQLiteMusic_stateRepository',
    'SQLiteBlessingRepository',
    'SQLitePrototypeRepository',
    'SQLiteFaction_ideologyRepository',
    'SQLiteKarmaRepository',
    'SQLiteCharacter_variantRepository',
    'SQLiteLegal_systemRepository',
    'SQLiteQuest_objectiveRepository',
    'SQLitePlot_branchRepository',
    'SQLiteWaypointRepository',
    'SQLiteProgression_eventRepository',
    'SQLiteNewspaperRepository',
    'SQLiteWardRepository',
    'SQLiteMemoryRepository',
    'SQLitePullRepository',
    'SQLiteHandoutRepository',
    'SQLiteBranch_pointRepository',
    'SQLiteWorld_eventRepository',
    'SQLiteSectRepository',
    'SQLiteEmpireRepository',
    'SQLiteQuest_chainRepository',
    'SQLiteChoiceRepository',
    'SQLiteRuneRepository',
    'SQLiteHolidayRepository',
    'SQLiteShaderRepository',
    'SQLiteTitleRepository',
    'SQLitePlayer_metricRepository',
    'SQLiteEpilogueRepository',
    'SQLiteMysteryRepository',
    'SQLiteWeather_patternRepository',
    'SQLiteActRepository',
    'SQLiteEpisodeRepository',
    'SQLiteTelevisionRepository',
    'SQLiteSiege_engineRepository',
    'SQLiteCustom_mapRepository',
    'SQLiteThemeRepository',
    'SQLiteCrafting_recipeRepository',
    'SQLiteSocial_classRepository',
    'SQLiteFaction_leaderRepository',
    'SQLiteRiddleRepository',
    'SQLiteFast_travel_pointRepository',
    'SQLiteMuseumRepository',
    'SQLiteTraitRepository',
    'SQLiteFamiliarRepository',
    'SQLiteEra_transitionRepository',
    'SQLiteTariffRepository',
    'SQLiteQuest_nodeRepository',
    'SQLiteDreamRepository',
    'SQLiteHoly_siteRepository',
    'SQLiteInventoryRepository',
    'SQLiteAffinityRepository',
    'SQLiteAlternate_realityRepository',
    'SQLiteMount_equipmentRepository',
    'SQLiteSound_effectRepository',
    'SQLiteInternetRepository',
    'SQLiteTime_periodRepository',
    'SQLiteSessionRepository',
    'SQLiteExperienceRepository',
    'SQLitePuzzleRepository',
    'SQLiteMotion_captureRepository',
    'SQLiteFortificationRepository',
    'SQLiteVoice_actorRepository',
    'SQLiteDimensionRepository',
    'SQLiteMusic_controlRepository',
    'SQLiteDubbingRepository',
    'SQLiteHidden_pathRepository',
    'SQLiteFleetRepository',
    'SQLiteSocial_mediaRepository',
    'SQLiteBarterRepository',
    'SQLiteCalendarRepository',
    'SQLiteSolsticeRepository',
    'SQLiteSchoolRepository',
    'SQLiteSlumsRepository',
    'SQLiteDisasterRepository',
    'SQLiteMasteryRepository',
    'SQLitePageRepository',
    'SQLiteMotifRepository',
    'SQLiteSpawn_pointRepository',
    'SQLiteWorkshop_entryRepository',
    'SQLiteEnvironmentRepository',
    'SQLiteTextureRepository',
    'SQLiteMoral_choiceRepository',
    'SQLiteVoice_lineRepository',
    'SQLiteFamineRepository',
    'SQLiteSession_dataRepository',
    'SQLitePatentRepository',
    'SQLiteArchiveRepository',
    'SQLiteConversion_rateRepository',
    'SQLiteScriptureRepository',
    'SQLiteSpaceshipRepository',
    'SQLiteBattalionRepository',
    'SQLitePhenomenonRepository',
    'SQLiteCompetitionRepository',
    'SQLitePlagueRepository',
    'SQLiteBlack_holeRepository',
    'SQLiteWitnessRepository',
    'SQLiteCursed_itemRepository',
    'SQLiteTimelineRepository',
    'SQLiteComponentRepository',
    'SQLiteCutsceneRepository',
    'SQLiteFaction_hierarchyRepository',
    'SQLiteMusic_trackRepository',
    'SQLiteTrapRepository',
    'SQLiteCrimeRepository',
    'SQLiteFood_chainRepository',
    'SQLiteReproductionRepository',
    'SQLiteRaidRepository',
    'SQLiteFlowchartRepository',
    'SQLiteScoreRepository',
    'SQLiteHonorRepository',
    'SQLiteStorylineRepository',
    'SQLiteLevel_upRepository',
    'SQLiteNebulaRepository',
    'SQLiteCodex_entryRepository',
    'SQLiteSubtitleRepository',
    'SQLiteDistrictRepository',
    'SQLiteQuest_prerequisiteRepository',
    'SQLiteMythical_armorRepository',
    'SQLiteRitualRepository',
    'SQLiteRed_herringRepository',
    'SQLitePetRepository',
    'SQLiteAtmosphereRepository',
    'SQLiteSocketRepository',
    'SQLiteFlashbackRepository',
    'SQLiteBadgeRepository',
    'SQLitePlazaRepository',
    'SQLiteMapRepository',
    'SQLiteEraRepository',
    'SQLiteTournamentRepository',
    'SQLiteShare_codeRepository',
    'SQLiteLocalizationRepository',
    'SQLiteMarket_squareRepository',
    'SQLiteResearch_centerRepository',
    'SQLiteHeatmapRepository',
    'SQLiteResearchRepository',
    'SQLiteRumorRepository',
    'SQLiteInventionRepository',
    'SQLiteCamera_pathRepository',
    'SQLiteEnigmaRepository',
    'SQLiteChekhovs_gunRepository',
    'SQLiteReputationRepository',
    'SQLiteParticleRepository',
    'SQLiteFaction_territoryRepository',
    'SQLiteCharacter_evolutionRepository',
    'SQLiteTeleporterRepository',
    'SQLiteShopRepository',
    'SQLiteArenaRepository',
    'SQLiteCurrencyRepository',
    'SQLiteExhibitionRepository',
    'SQLiteMigrationRepository',
    'SQLiteForeshadowingRepository',
    'SQLiteSkyboxRepository',
    'SQLiteQuest_reward_tierRepository',
    'SQLiteCharacterRepository',
    'SQLiteEvolutionRepository',
    'SQLiteHibernationRepository',
    'SQLiteConsequenceRepository',
    'SQLiteDivine_itemRepository',
    'SQLiteEaster_eggRepository',
    'SQLiteVehicleRepository',
    'SQLiteWeapon_systemRepository',
    'SQLitePort_districtRepository',
    'SQLiteLibraryRepository',
    'SQLiteTokenboardRepository',
    'SQLiteLightingRepository',
    'SQLiteCheckpointRepository',
    'SQLiteUniversityRepository',
    'SQLiteTrophyRepository',
    'SQLiteSummonRepository',
    'SQLiteKingdomRepository',
    'SQLiteLawRepository',
    'SQLiteTemplateRepository',
    'SQLiteAchievementRepository',
    'SQLiteTransitionRepository',
    'SQLiteTaxRepository',
    'SQLiteLawyerRepository',
    'SQLiteQuest_giverRepository',
    'SQLitePriceRepository',
    'SQLiteEndingRepository',
    'SQLitePortalRepository',
    'SQLiteTradeRepository',
    'SQLiteOathRepository',
    'SQLiteAmbientRepository',
    'SQLiteMoonRepository',
    'SQLiteExtinctionRepository',
    'SQLiteDungeonRepository',
    'SQLiteJournal_pageRepository',
    'SQLiteGalaxyRepository',
    'SQLitePlayer_profileRepository',
    'SQLiteNoble_districtRepository',
    'SQLiteDispositionRepository',
    'SQLiteJuryRepository',
    'SQLiteCeremonyRepository',


# Placeholder repositories

